# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-23 12:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anwendungen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Anwendungen',
                'verbose_name': 'Anwendung',
                'db_table': 'anwendungen',
            },
        ),
        migrations.CreateModel(
            name='Glossareintraege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=250)),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name_plural': 'Glossareinträge',
                'verbose_name': 'Glossareintrag',
                'db_table': 'glossarentraege',
            },
        ),
        migrations.CreateModel(
            name='Notizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notizen',
                'verbose_name': 'Notiz',
                'db_table': 'notizen',
            },
        ),
        migrations.CreateModel(
            name='Rollen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolle', models.CharField(max_length=250, verbose_name='Rolle')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('anwendung', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Anwendungen', verbose_name='Anwendung')),
            ],
            options={
                'verbose_name_plural': 'Rollen',
                'verbose_name': 'Rolle',
                'db_table': 'rollen',
            },
        ),
        migrations.CreateModel(
            name='Schlagworte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schlagwort', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Schlagworte',
                'verbose_name': 'Schlagwort',
                'db_table': 'schlagworte',
            },
        ),
        migrations.CreateModel(
            name='Userstories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=150)),
                ('text_als', models.TextField(verbose_name='Möchte ich...')),
                ('text_damit', models.TextField(verbose_name='Damit ich...')),
                ('erfuellungsgrad', models.PositiveSmallIntegerField(verbose_name='Erfüllungsgrad')),
                ('anwendung', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Anwendungen', verbose_name='Anwendung')),
                ('rolle', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Rollen', verbose_name='Als...')),
                ('schlagworte', models.ManyToManyField(blank=True, to='webapp.Schlagworte', verbose_name='Schlagworte')),
            ],
            options={
                'verbose_name_plural': 'Userstories',
                'verbose_name': 'Userstory',
                'db_table': 'userstories',
            },
        ),
        migrations.AddField(
            model_name='notizen',
            name='userstory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Userstories'),
        ),
    ]
