# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-23 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_anwendungen_beschreibung'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anwendungen',
            name='beschreibung',
        ),
    ]
